name: Add Test

on:
  pull_request:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  codesandbox-comment:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}